spring.application.name=api-gateway

server.port=8080
spring.cloud.gateway.server.webmvc.routes[0].id=core-service-books
spring.cloud.gateway.server.webmvc.routes[0].uri=${CORE_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/books/**

spring.cloud.gateway.server.webmvc.routes[1].id=core-service-health
spring.cloud.gateway.server.webmvc.routes[1].uri=${CORE_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/core-service/**

spring.cloud.gateway.server.webmvc.routes[2].id=support-service
spring.cloud.gateway.server.webmvc.routes[2].uri=${SUPPORT_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/support-service/**

spring.cloud.gateway.server.webmvc.routes[3].id=support-service-fines
spring.cloud.gateway.server.webmvc.routes[3].uri=${SUPPORT_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/fines/**

spring.cloud.gateway.server.webmvc.routes[4].id=support-service-borrows
spring.cloud.gateway.server.webmvc.routes[4].uri=${SUPPORT_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/borrows/**

spring.cloud.gateway.server.webmvc.routes[5].id=support-service-notifications
spring.cloud.gateway.server.webmvc.routes[5].uri=${SUPPORT_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/notifications/**

spring.cloud.gateway.server.webmvc.routes[6].id=core-service-auth
spring.cloud.gateway.server.webmvc.routes[6].uri=${CORE_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/auth/**
