spring.application.name=support-service
server.port=8082

core-service.url=${CORE_SERVICE_URL:http://localhost:8081}

spring.datasource.url=jdbc:postgresql://localhost:5433/support
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# Logging
logging.level.root=INFO
logging.level.io.github.seaniestack.supportservice=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
