spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
