spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/coredb}
    username: ${DB_USER:coreuser}
    password: ${DB_PASS:corepass}
