spring.application.name=core-service
server.port=8081

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.datasource.url=jdbc:postgresql://localhost:5432/core
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=${JWT_SECRET:local-dev-only-change-me-please-use-a-long-random-secret-key-at-least-32-chars}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
